[project]
name = "titanic-survival-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.0",
    "scikit-learn==1.4.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
